project:
  type: website
  output-dir: docs
  resources:
    - "media/weber_curriculumvitae.pdf"

website:
  title: "alexisweber.github.io"
  navbar:
    background: dark
    title: false
    left:
      - text: About
        href: "#about"
      - text: Skills
        href: "#skills"
      - text: Projects
        href: "#projects"
      - text: Pubs
        href: "#publication"
      - text: Certificates
        href: "#certificates"
      - text: Timeline
        href: "#timeline"
      - text: News
        href: "#news"
format:
  html:
    theme:
      - cosmo
      - brand
    css: 
      - styles.css
      - media/icons/bootstrap-icons.css  
    toc: false
    include-after-body:
      - partials/_footer.html
about: 
  template: trestles
  id: about
  image-shape: round
  image-width: 17em
  links:
    - text: "<span class='about-icon-btn' aria-label='LinkedIn'><i class='bi bi-linkedin'></i></span>"
      href: https://www.linkedin.com/in/alexiswebercompbio/
    - text: "<span class='about-icon-btn' aria-label='GitHub'><i class='bi bi-github'></i></span>"
      href: https://github.com/alexisweber
    - text: "<i class='bi bi-file-earmark-text'></i>"
      href: media/weber_curriculumvitae.pdf
      #download: true
    


