project:
  type: website
  output-dir: docs

website:
  title: "alexisweber.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: 
      - styles.css
      - media/icons/bootstrap-icons.css  
    toc: true
    


