project:
  type: website
  output-dir: docs

website:
  title: "Alexis Weber"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
  page-navigation: true
  search: true

format:
  html:
    theme: flatly
    toc: true
    toc-location: right
    css: styles.css  

editor: visual

# make sure static files like your PDF are copied
resources:
  - assets/**
  - media/**
